<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>练习生命周期</title>
</head>

<body>

	<script type="text/javascript">
/* async、await错误处理
JavaScript异步请求肯定会有请求失败的情况，上面也说到了async返回的是一个Promise对象。既然是返回一个Promise对象的话那处理当异步请求发生错误的时候我们就要处理reject的状态了。

在Promise中当请求reject的时候我们可以使用catch。为了保持代码的健壮性使用async、await的时候我们使用try catch来处理错误。
 */
 async function catchErr() {
     try {
         const errRes = await new Promise((resolve, reject) => {
               setTimeout(() => {
                   reject("http error...");
                }, 1000);
          );
               //平常我们也可以在await请求成功后通过判断当前status是不是200来判断请求是否成功
               // console.log(errRes.status, errRes.statusText);
       } catch(err) {
            console.log(err);
       }
}
catchErr(); //http error...
// 以上就是async、await使用try catch 处理错误的方式。
// 虽然async、await也使用到了Promise但是却减少了Promise的then处理使得整个异步请求代码清爽了许多。


</script>
</body>
</html>